FROM python:3.11-slim

RUN apt-get update && \
    apt-get install -y \
        build-essential \
        curl \
    && apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

WORKDIR /app

COPY requirements-sudachi.txt .

RUN pip install --no-cache-dir -r requirements-sudachi.txt
