version: '3.8'

services:
  web:
    build: .
    ports:
      - "7860:7860"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - DYNAMODB_TABLE=${DYNAMODB_TABLE}
      - SAGEMAKER_ENDPOINT=${SAGEMAKER_ENDPOINT}
    volumes:
      - .:/app