services:
  webapp:
    build: .
    ports:
      - 8501:8501
    environment:
      - BACKEND_SERVICE_URL=http://backend:8888/v1/vocab_generator
    volumes:
      - .:/app
    depends_on:
      - backend

  backend:
    build: ../mega-service
    ports:
      - 8888:8888
    environment:
      - OLLAMA_HOST=ollama
      - OLLAMA_PORT=11434
      - OLLAMA_MODEL=llama3.2:1b
    depends_on:
      ollama:
        condition: service_healthy

  ollama:
    image: ollama/ollama
    ports:
      - 11434:11434
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ollama list || exit 1
      interval: 3s
      timeout: 3s
      retries: 3

volumes:
  ollama_data:
    name: ollama-data

networks:
  default:
    driver: bridge 