services:
  minio:
    image: minio/minio:RELEASE.2025-02-28T09-55-16Z
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: "minio_access_key"
      MINIO_SECRET_KEY: "minio_secret_key"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      MINIO_URL: http://minio:9000
      MINIO_ACCESS_KEY: "minio_access_key"
      MINIO_SECRET_KEY: "minio_secret_key"
      BUCKET_NAME: haiku
    depends_on:
      - minio

volumes:
  minio_data:
