services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - 11434:11434
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ollama list || exit 1
      interval: 3s
      timeout: 3s
      retries: 3

  vocab-service:
    build: .
    ports:
      - 8888:8888
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_MODEL=llama2:1b
    depends_on:
      ollama:
        condition: service_healthy

volumes:
  ollama_data:
    name: ollama-data